apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.appname }}-{{ .Values.env }}
  labels:
{{- with .Values.labels }}
{{- toYaml . |nindent 4 }}
{{- end }}  
type: Opaque
data:
{{- with .Values.secretvalues }}
{{- toYaml . |nindent 4 }}
{{- end }}