apiVersion: v1
data:
{{- with .Values.configvalues }}
{{- toYaml . |nindent 4 }}
{{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.appname }}-{{ .Values.env }}
  labels:
{{- with .Values.labels }}
{{- toYaml . |nindent 4 }}
{{- end }}  