apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{- with .Values.labels }}
{{- toYaml . |nindent 4 }}
{{- end }}
  name: {{ .Values.name }}
  namespace: {{ .Values.appname }}-{{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{- with .Values.labels }}
{{- toYaml . |nindent 8 }}
{{- end }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
{{- with .Values.labels }}
{{- toYaml . |nindent 8 }}
{{- end }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ .Values.podname }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
              path: /
              port: http
        readinessProbe:
          httpGet:
              path: /
              port: http
        resources:
	  {{- toYaml .Values.resources | nindent 12 }}
status: {}

