apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.appname }}-{{ .Values.env }}
type: Opaque
data:
{{- with .Values.secretvalues }}
{{- toYaml . |nindent 4 }}
{{- end }}