apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
{{- with .Values.labels }}
{{- toYaml . |nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
 {{- with .Values.labels }}
{{- toYaml . |nindent 4 }}
{{- end }}